---
http_interactions:
- request:
    method: get
    uri: https://api.webmaster.yandex.net/v4/user/845457627/hosts?mode=DEBUG
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/rss+xml
      Authorization:
      - OAuth AQAAAAAyZKjbAAUEelU5CLeOe0JAu3i-GsszWNU
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - api.webmaster.yandex.net
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 04 Jun 2019 00:23:15 GMT
      Content-Type:
      - application/json;charset=UTF-8
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"hosts":[{"host_id":"http:orel.test-pulscen.ru:80","ascii_host_url":"http://orel.test-pulscen.ru/","unicode_host_url":"http://orel.test-pulscen.ru/","verified":true,"main_mirror":null}]}'
    http_version: 
  recorded_at: Tue, 04 Jun 2019 05:23:14 GMT
recorded_with: VCR 5.0.0
